# Generated by Django 5.2.4 on 2025-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='workorder',
            name='other_type',
            field=models.CharField(blank=True, help_text='Specify if type is Others', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='type',
            field=models.CharField(choices=[('desktop_laptop', 'Desktop/Laptop Computer'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('lan_internet', 'LAN/Internet'), ('other', 'Others')], default='desktop_laptop', max_length=20),
        ),
    ]
