# Generated by Django 5.2.4 on 2025-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_remove_workorder_issue_type_workorder_other_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_going', 'On Going'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
