# Generated by Django 5.2.6 on 2025-09-11 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderhistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RenameField(
            model_name='workorderhistory',
            old_name='timestamp',
            new_name='changed_at',
        ),
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('checkup', 'Checkup'), ('cleaning', 'Cleaning'), ('data_backup_recovery', 'Data Backup and Recovery'), ('installation_setup', 'Installation and Setup'), ('reformatting_reinstallation', 'Reformatting and Reinstallation'), ('replacement', 'Replacement'), ('relocation_reassignment', 'Relocation/Reassignment'), ('update_upgrade_software', 'Update/Upgrade Software')], default='repair', max_length=30),
        ),
        migrations.AddField(
            model_name='workorder',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number of the item (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(default='None', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
    ]
