# Generated by Django 5.2.4 on 2025-07-17 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('checkup', 'Checkup')], default='repair', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number of the item (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
