# Generated by Django 5.2.4 on 2025-07-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_category_workorder_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('checkup', 'Checkup')], default='Repair', max_length=20),
        ),
    ]
