# Generated by Django 5.2.6 on 2025-09-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_status_category_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='category_new',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status_new',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workordercategory'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workorderstatus'),
        ),
        migrations.AlterField(
            model_name='workordercategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workorderstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
