# Generated by Django 5.2.4 on 2025-07-23 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_workorder_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderhistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RenameField(
            model_name='workorderhistory',
            old_name='timestamp',
            new_name='changed_at',
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
    ]
