# Generated by Django 5.2.4 on 2025-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_alter_workorderhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(default='No remarks', max_length=150),
            preserve_default=False,
        ),
    ]
