# Generated by Django 5.2.6 on 2025-09-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_add_workorder_status_and_category'),
        ('workorders', '0005_workorder_status_and_category'),
        ('workorders', '0006_remove_workorder_category_new_and_more'),
    ]

    operations = [
    ]
