# Generated by Django 5.2.4 on 2025-07-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_alter_workorder_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('checkup', 'Checkup'), ('cleaning', 'Cleaning'), ('data_backup_recovery', 'Data Backup and Recovery'), ('installation_setup', 'Installation and Setup'), ('reformatting_reinstallation', 'Reformatting and Reinstallation'), ('replacement', 'Replacement'), ('relocation_reassignment', 'Relocation/Reassignment'), ('update_upgrade_software', 'Update/Upgrade Software')], default='repair', max_length=30),
        ),
    ]
