# Generated by Django 5.2.6 on 2025-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_merge_20250911_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordercategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workorderstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
