# Generated by Django 5.2.4 on 2025-07-29 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_alter_workorder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
