# Generated by Django 5.2.4 on 2025-07-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
